// Generated by scripts/generate-lesson-regions.mjs. Do not edit manually.

export type LessonRegionDistrict = Readonly<{
  code: string
  label: string
  queryValue: string
}>

export type LessonRegion = Readonly<{
  sourceCode: string
  label: string
  queryValue: string
  provinceOnly: boolean
  districts: readonly LessonRegionDistrict[]
}>

export const lessonRegionSource = {
  snapshotDate: "2026-06-30",
  sha256: "accc0a93dddefc5e01135d133fbdcd3425d24a8aeb14b90c928f8a1d680f7647",
  url: "https://www.data.go.kr/cmm/cmm/fileDownload.do?atchFileId=FILE_000000003676587&fileDetailSn=1&insertDataPrcus=N",
} as const

export const lessonRegions = [
  {
    sourceCode: "1100000000",
    label: "서울특별시",
    queryValue: "서울특별시",
    provinceOnly: false,
    districts: [
      {
        code: "1111000000",
        label: "종로구",
        queryValue: "서울특별시 종로구",
      },
      {
        code: "1114000000",
        label: "중구",
        queryValue: "서울특별시 중구",
      },
      {
        code: "1117000000",
        label: "용산구",
        queryValue: "서울특별시 용산구",
      },
      {
        code: "1120000000",
        label: "성동구",
        queryValue: "서울특별시 성동구",
      },
      {
        code: "1121500000",
        label: "광진구",
        queryValue: "서울특별시 광진구",
      },
      {
        code: "1123000000",
        label: "동대문구",
        queryValue: "서울특별시 동대문구",
      },
      {
        code: "1126000000",
        label: "중랑구",
        queryValue: "서울특별시 중랑구",
      },
      {
        code: "1129000000",
        label: "성북구",
        queryValue: "서울특별시 성북구",
      },
      {
        code: "1130500000",
        label: "강북구",
        queryValue: "서울특별시 강북구",
      },
      {
        code: "1132000000",
        label: "도봉구",
        queryValue: "서울특별시 도봉구",
      },
      {
        code: "1135000000",
        label: "노원구",
        queryValue: "서울특별시 노원구",
      },
      {
        code: "1138000000",
        label: "은평구",
        queryValue: "서울특별시 은평구",
      },
      {
        code: "1141000000",
        label: "서대문구",
        queryValue: "서울특별시 서대문구",
      },
      {
        code: "1144000000",
        label: "마포구",
        queryValue: "서울특별시 마포구",
      },
      {
        code: "1147000000",
        label: "양천구",
        queryValue: "서울특별시 양천구",
      },
      {
        code: "1150000000",
        label: "강서구",
        queryValue: "서울특별시 강서구",
      },
      {
        code: "1153000000",
        label: "구로구",
        queryValue: "서울특별시 구로구",
      },
      {
        code: "1154500000",
        label: "금천구",
        queryValue: "서울특별시 금천구",
      },
      {
        code: "1156000000",
        label: "영등포구",
        queryValue: "서울특별시 영등포구",
      },
      {
        code: "1159000000",
        label: "동작구",
        queryValue: "서울특별시 동작구",
      },
      {
        code: "1162000000",
        label: "관악구",
        queryValue: "서울특별시 관악구",
      },
      {
        code: "1165000000",
        label: "서초구",
        queryValue: "서울특별시 서초구",
      },
      {
        code: "1168000000",
        label: "강남구",
        queryValue: "서울특별시 강남구",
      },
      {
        code: "1171000000",
        label: "송파구",
        queryValue: "서울특별시 송파구",
      },
      {
        code: "1174000000",
        label: "강동구",
        queryValue: "서울특별시 강동구",
      },
    ],
  },
  {
    sourceCode: "2600000000",
    label: "부산광역시",
    queryValue: "부산광역시",
    provinceOnly: false,
    districts: [
      {
        code: "2611000000",
        label: "중구",
        queryValue: "부산광역시 중구",
      },
      {
        code: "2614000000",
        label: "서구",
        queryValue: "부산광역시 서구",
      },
      {
        code: "2617000000",
        label: "동구",
        queryValue: "부산광역시 동구",
      },
      {
        code: "2620000000",
        label: "영도구",
        queryValue: "부산광역시 영도구",
      },
      {
        code: "2623000000",
        label: "부산진구",
        queryValue: "부산광역시 부산진구",
      },
      {
        code: "2626000000",
        label: "동래구",
        queryValue: "부산광역시 동래구",
      },
      {
        code: "2629000000",
        label: "남구",
        queryValue: "부산광역시 남구",
      },
      {
        code: "2632000000",
        label: "북구",
        queryValue: "부산광역시 북구",
      },
      {
        code: "2635000000",
        label: "해운대구",
        queryValue: "부산광역시 해운대구",
      },
      {
        code: "2638000000",
        label: "사하구",
        queryValue: "부산광역시 사하구",
      },
      {
        code: "2641000000",
        label: "금정구",
        queryValue: "부산광역시 금정구",
      },
      {
        code: "2644000000",
        label: "강서구",
        queryValue: "부산광역시 강서구",
      },
      {
        code: "2647000000",
        label: "연제구",
        queryValue: "부산광역시 연제구",
      },
      {
        code: "2650000000",
        label: "수영구",
        queryValue: "부산광역시 수영구",
      },
      {
        code: "2653000000",
        label: "사상구",
        queryValue: "부산광역시 사상구",
      },
      {
        code: "2671000000",
        label: "기장군",
        queryValue: "부산광역시 기장군",
      },
    ],
  },
  {
    sourceCode: "2700000000",
    label: "대구광역시",
    queryValue: "대구광역시",
    provinceOnly: false,
    districts: [
      {
        code: "2711000000",
        label: "중구",
        queryValue: "대구광역시 중구",
      },
      {
        code: "2714000000",
        label: "동구",
        queryValue: "대구광역시 동구",
      },
      {
        code: "2717000000",
        label: "서구",
        queryValue: "대구광역시 서구",
      },
      {
        code: "2720000000",
        label: "남구",
        queryValue: "대구광역시 남구",
      },
      {
        code: "2723000000",
        label: "북구",
        queryValue: "대구광역시 북구",
      },
      {
        code: "2726000000",
        label: "수성구",
        queryValue: "대구광역시 수성구",
      },
      {
        code: "2729000000",
        label: "달서구",
        queryValue: "대구광역시 달서구",
      },
      {
        code: "2771000000",
        label: "달성군",
        queryValue: "대구광역시 달성군",
      },
      {
        code: "2772000000",
        label: "군위군",
        queryValue: "대구광역시 군위군",
      },
    ],
  },
  {
    sourceCode: "2800000000",
    label: "인천광역시",
    queryValue: "인천광역시",
    provinceOnly: false,
    districts: [
      {
        code: "2812500000",
        label: "제물포구",
        queryValue: "인천광역시 제물포구",
      },
      {
        code: "2815500000",
        label: "영종구",
        queryValue: "인천광역시 영종구",
      },
      {
        code: "2817700000",
        label: "미추홀구",
        queryValue: "인천광역시 미추홀구",
      },
      {
        code: "2818500000",
        label: "연수구",
        queryValue: "인천광역시 연수구",
      },
      {
        code: "2820000000",
        label: "남동구",
        queryValue: "인천광역시 남동구",
      },
      {
        code: "2823700000",
        label: "부평구",
        queryValue: "인천광역시 부평구",
      },
      {
        code: "2824500000",
        label: "계양구",
        queryValue: "인천광역시 계양구",
      },
      {
        code: "2827500000",
        label: "서해구",
        queryValue: "인천광역시 서해구",
      },
      {
        code: "2829000000",
        label: "검단구",
        queryValue: "인천광역시 검단구",
      },
      {
        code: "2871000000",
        label: "강화군",
        queryValue: "인천광역시 강화군",
      },
      {
        code: "2872000000",
        label: "옹진군",
        queryValue: "인천광역시 옹진군",
      },
    ],
  },
  {
    sourceCode: "1200000000",
    label: "광주광역시",
    queryValue: "광주광역시",
    provinceOnly: false,
    districts: [
      {
        code: "1221000000",
        label: "동구",
        queryValue: "광주광역시 동구",
      },
      {
        code: "1224000000",
        label: "서구",
        queryValue: "광주광역시 서구",
      },
      {
        code: "1227000000",
        label: "남구",
        queryValue: "광주광역시 남구",
      },
      {
        code: "1230000000",
        label: "북구",
        queryValue: "광주광역시 북구",
      },
      {
        code: "1233000000",
        label: "광산구",
        queryValue: "광주광역시 광산구",
      },
    ],
  },
  {
    sourceCode: "3000000000",
    label: "대전광역시",
    queryValue: "대전광역시",
    provinceOnly: false,
    districts: [
      {
        code: "3011000000",
        label: "동구",
        queryValue: "대전광역시 동구",
      },
      {
        code: "3014000000",
        label: "중구",
        queryValue: "대전광역시 중구",
      },
      {
        code: "3017000000",
        label: "서구",
        queryValue: "대전광역시 서구",
      },
      {
        code: "3020000000",
        label: "유성구",
        queryValue: "대전광역시 유성구",
      },
      {
        code: "3023000000",
        label: "대덕구",
        queryValue: "대전광역시 대덕구",
      },
    ],
  },
  {
    sourceCode: "3100000000",
    label: "울산광역시",
    queryValue: "울산광역시",
    provinceOnly: false,
    districts: [
      {
        code: "3111000000",
        label: "중구",
        queryValue: "울산광역시 중구",
      },
      {
        code: "3114000000",
        label: "남구",
        queryValue: "울산광역시 남구",
      },
      {
        code: "3117000000",
        label: "동구",
        queryValue: "울산광역시 동구",
      },
      {
        code: "3120000000",
        label: "북구",
        queryValue: "울산광역시 북구",
      },
      {
        code: "3171000000",
        label: "울주군",
        queryValue: "울산광역시 울주군",
      },
    ],
  },
  {
    sourceCode: "3600000000",
    label: "세종특별자치시",
    queryValue: "세종특별자치시",
    provinceOnly: true,
    districts: [],
  },
  {
    sourceCode: "4100000000",
    label: "경기도",
    queryValue: "경기도",
    provinceOnly: false,
    districts: [
      {
        code: "4111000000",
        label: "수원시",
        queryValue: "경기도 수원시",
      },
      {
        code: "4111100000",
        label: "수원시장안구",
        queryValue: "경기도 수원시장안구",
      },
      {
        code: "4111300000",
        label: "수원시권선구",
        queryValue: "경기도 수원시권선구",
      },
      {
        code: "4111500000",
        label: "수원시팔달구",
        queryValue: "경기도 수원시팔달구",
      },
      {
        code: "4111700000",
        label: "수원시영통구",
        queryValue: "경기도 수원시영통구",
      },
      {
        code: "4113000000",
        label: "성남시",
        queryValue: "경기도 성남시",
      },
      {
        code: "4113100000",
        label: "성남시수정구",
        queryValue: "경기도 성남시수정구",
      },
      {
        code: "4113300000",
        label: "성남시중원구",
        queryValue: "경기도 성남시중원구",
      },
      {
        code: "4113500000",
        label: "성남시분당구",
        queryValue: "경기도 성남시분당구",
      },
      {
        code: "4115000000",
        label: "의정부시",
        queryValue: "경기도 의정부시",
      },
      {
        code: "4117000000",
        label: "안양시",
        queryValue: "경기도 안양시",
      },
      {
        code: "4117100000",
        label: "안양시만안구",
        queryValue: "경기도 안양시만안구",
      },
      {
        code: "4117300000",
        label: "안양시동안구",
        queryValue: "경기도 안양시동안구",
      },
      {
        code: "4119000000",
        label: "부천시",
        queryValue: "경기도 부천시",
      },
      {
        code: "4119200000",
        label: "부천시원미구",
        queryValue: "경기도 부천시원미구",
      },
      {
        code: "4119400000",
        label: "부천시소사구",
        queryValue: "경기도 부천시소사구",
      },
      {
        code: "4119600000",
        label: "부천시오정구",
        queryValue: "경기도 부천시오정구",
      },
      {
        code: "4121000000",
        label: "광명시",
        queryValue: "경기도 광명시",
      },
      {
        code: "4122000000",
        label: "평택시",
        queryValue: "경기도 평택시",
      },
      {
        code: "4125000000",
        label: "동두천시",
        queryValue: "경기도 동두천시",
      },
      {
        code: "4127000000",
        label: "안산시",
        queryValue: "경기도 안산시",
      },
      {
        code: "4127100000",
        label: "안산시상록구",
        queryValue: "경기도 안산시상록구",
      },
      {
        code: "4127300000",
        label: "안산시단원구",
        queryValue: "경기도 안산시단원구",
      },
      {
        code: "4128000000",
        label: "고양시",
        queryValue: "경기도 고양시",
      },
      {
        code: "4128100000",
        label: "고양시덕양구",
        queryValue: "경기도 고양시덕양구",
      },
      {
        code: "4128500000",
        label: "고양시일산동구",
        queryValue: "경기도 고양시일산동구",
      },
      {
        code: "4128700000",
        label: "고양시일산서구",
        queryValue: "경기도 고양시일산서구",
      },
      {
        code: "4129000000",
        label: "과천시",
        queryValue: "경기도 과천시",
      },
      {
        code: "4131000000",
        label: "구리시",
        queryValue: "경기도 구리시",
      },
      {
        code: "4136000000",
        label: "남양주시",
        queryValue: "경기도 남양주시",
      },
      {
        code: "4137000000",
        label: "오산시",
        queryValue: "경기도 오산시",
      },
      {
        code: "4139000000",
        label: "시흥시",
        queryValue: "경기도 시흥시",
      },
      {
        code: "4141000000",
        label: "군포시",
        queryValue: "경기도 군포시",
      },
      {
        code: "4143000000",
        label: "의왕시",
        queryValue: "경기도 의왕시",
      },
      {
        code: "4145000000",
        label: "하남시",
        queryValue: "경기도 하남시",
      },
      {
        code: "4146000000",
        label: "용인시",
        queryValue: "경기도 용인시",
      },
      {
        code: "4146100000",
        label: "용인시처인구",
        queryValue: "경기도 용인시처인구",
      },
      {
        code: "4146300000",
        label: "용인시기흥구",
        queryValue: "경기도 용인시기흥구",
      },
      {
        code: "4146500000",
        label: "용인시수지구",
        queryValue: "경기도 용인시수지구",
      },
      {
        code: "4148000000",
        label: "파주시",
        queryValue: "경기도 파주시",
      },
      {
        code: "4150000000",
        label: "이천시",
        queryValue: "경기도 이천시",
      },
      {
        code: "4155000000",
        label: "안성시",
        queryValue: "경기도 안성시",
      },
      {
        code: "4157000000",
        label: "김포시",
        queryValue: "경기도 김포시",
      },
      {
        code: "4159000000",
        label: "화성시",
        queryValue: "경기도 화성시",
      },
      {
        code: "4159100000",
        label: "화성시만세구",
        queryValue: "경기도 화성시만세구",
      },
      {
        code: "4159300000",
        label: "화성시효행구",
        queryValue: "경기도 화성시효행구",
      },
      {
        code: "4159500000",
        label: "화성시병점구",
        queryValue: "경기도 화성시병점구",
      },
      {
        code: "4159700000",
        label: "화성시동탄구",
        queryValue: "경기도 화성시동탄구",
      },
      {
        code: "4161000000",
        label: "광주시",
        queryValue: "경기도 광주시",
      },
      {
        code: "4163000000",
        label: "양주시",
        queryValue: "경기도 양주시",
      },
      {
        code: "4165000000",
        label: "포천시",
        queryValue: "경기도 포천시",
      },
      {
        code: "4167000000",
        label: "여주시",
        queryValue: "경기도 여주시",
      },
      {
        code: "4180000000",
        label: "연천군",
        queryValue: "경기도 연천군",
      },
      {
        code: "4182000000",
        label: "가평군",
        queryValue: "경기도 가평군",
      },
      {
        code: "4183000000",
        label: "양평군",
        queryValue: "경기도 양평군",
      },
    ],
  },
  {
    sourceCode: "5100000000",
    label: "강원특별자치도",
    queryValue: "강원특별자치도",
    provinceOnly: false,
    districts: [
      {
        code: "5111000000",
        label: "춘천시",
        queryValue: "강원특별자치도 춘천시",
      },
      {
        code: "5113000000",
        label: "원주시",
        queryValue: "강원특별자치도 원주시",
      },
      {
        code: "5115000000",
        label: "강릉시",
        queryValue: "강원특별자치도 강릉시",
      },
      {
        code: "5117000000",
        label: "동해시",
        queryValue: "강원특별자치도 동해시",
      },
      {
        code: "5119000000",
        label: "태백시",
        queryValue: "강원특별자치도 태백시",
      },
      {
        code: "5121000000",
        label: "속초시",
        queryValue: "강원특별자치도 속초시",
      },
      {
        code: "5123000000",
        label: "삼척시",
        queryValue: "강원특별자치도 삼척시",
      },
      {
        code: "5172000000",
        label: "홍천군",
        queryValue: "강원특별자치도 홍천군",
      },
      {
        code: "5173000000",
        label: "횡성군",
        queryValue: "강원특별자치도 횡성군",
      },
      {
        code: "5175000000",
        label: "영월군",
        queryValue: "강원특별자치도 영월군",
      },
      {
        code: "5176000000",
        label: "평창군",
        queryValue: "강원특별자치도 평창군",
      },
      {
        code: "5177000000",
        label: "정선군",
        queryValue: "강원특별자치도 정선군",
      },
      {
        code: "5178000000",
        label: "철원군",
        queryValue: "강원특별자치도 철원군",
      },
      {
        code: "5179000000",
        label: "화천군",
        queryValue: "강원특별자치도 화천군",
      },
      {
        code: "5180000000",
        label: "양구군",
        queryValue: "강원특별자치도 양구군",
      },
      {
        code: "5181000000",
        label: "인제군",
        queryValue: "강원특별자치도 인제군",
      },
      {
        code: "5182000000",
        label: "고성군",
        queryValue: "강원특별자치도 고성군",
      },
      {
        code: "5183000000",
        label: "양양군",
        queryValue: "강원특별자치도 양양군",
      },
    ],
  },
  {
    sourceCode: "4300000000",
    label: "충청북도",
    queryValue: "충청북도",
    provinceOnly: false,
    districts: [
      {
        code: "4311000000",
        label: "청주시",
        queryValue: "충청북도 청주시",
      },
      {
        code: "4311100000",
        label: "청주시상당구",
        queryValue: "충청북도 청주시상당구",
      },
      {
        code: "4311200000",
        label: "청주시서원구",
        queryValue: "충청북도 청주시서원구",
      },
      {
        code: "4311300000",
        label: "청주시흥덕구",
        queryValue: "충청북도 청주시흥덕구",
      },
      {
        code: "4311400000",
        label: "청주시청원구",
        queryValue: "충청북도 청주시청원구",
      },
      {
        code: "4313000000",
        label: "충주시",
        queryValue: "충청북도 충주시",
      },
      {
        code: "4315000000",
        label: "제천시",
        queryValue: "충청북도 제천시",
      },
      {
        code: "4372000000",
        label: "보은군",
        queryValue: "충청북도 보은군",
      },
      {
        code: "4373000000",
        label: "옥천군",
        queryValue: "충청북도 옥천군",
      },
      {
        code: "4374000000",
        label: "영동군",
        queryValue: "충청북도 영동군",
      },
      {
        code: "4374500000",
        label: "증평군",
        queryValue: "충청북도 증평군",
      },
      {
        code: "4375000000",
        label: "진천군",
        queryValue: "충청북도 진천군",
      },
      {
        code: "4376000000",
        label: "괴산군",
        queryValue: "충청북도 괴산군",
      },
      {
        code: "4377000000",
        label: "음성군",
        queryValue: "충청북도 음성군",
      },
      {
        code: "4380000000",
        label: "단양군",
        queryValue: "충청북도 단양군",
      },
    ],
  },
  {
    sourceCode: "4400000000",
    label: "충청남도",
    queryValue: "충청남도",
    provinceOnly: false,
    districts: [
      {
        code: "4413000000",
        label: "천안시",
        queryValue: "충청남도 천안시",
      },
      {
        code: "4413100000",
        label: "천안시동남구",
        queryValue: "충청남도 천안시동남구",
      },
      {
        code: "4413300000",
        label: "천안시서북구",
        queryValue: "충청남도 천안시서북구",
      },
      {
        code: "4415000000",
        label: "공주시",
        queryValue: "충청남도 공주시",
      },
      {
        code: "4418000000",
        label: "보령시",
        queryValue: "충청남도 보령시",
      },
      {
        code: "4420000000",
        label: "아산시",
        queryValue: "충청남도 아산시",
      },
      {
        code: "4421000000",
        label: "서산시",
        queryValue: "충청남도 서산시",
      },
      {
        code: "4423000000",
        label: "논산시",
        queryValue: "충청남도 논산시",
      },
      {
        code: "4425000000",
        label: "계룡시",
        queryValue: "충청남도 계룡시",
      },
      {
        code: "4427000000",
        label: "당진시",
        queryValue: "충청남도 당진시",
      },
      {
        code: "4471000000",
        label: "금산군",
        queryValue: "충청남도 금산군",
      },
      {
        code: "4476000000",
        label: "부여군",
        queryValue: "충청남도 부여군",
      },
      {
        code: "4477000000",
        label: "서천군",
        queryValue: "충청남도 서천군",
      },
      {
        code: "4479000000",
        label: "청양군",
        queryValue: "충청남도 청양군",
      },
      {
        code: "4480000000",
        label: "홍성군",
        queryValue: "충청남도 홍성군",
      },
      {
        code: "4481000000",
        label: "예산군",
        queryValue: "충청남도 예산군",
      },
      {
        code: "4482500000",
        label: "태안군",
        queryValue: "충청남도 태안군",
      },
    ],
  },
  {
    sourceCode: "5200000000",
    label: "전북특별자치도",
    queryValue: "전북특별자치도",
    provinceOnly: false,
    districts: [
      {
        code: "5211000000",
        label: "전주시",
        queryValue: "전북특별자치도 전주시",
      },
      {
        code: "5211100000",
        label: "전주시완산구",
        queryValue: "전북특별자치도 전주시완산구",
      },
      {
        code: "5211300000",
        label: "전주시덕진구",
        queryValue: "전북특별자치도 전주시덕진구",
      },
      {
        code: "5213000000",
        label: "군산시",
        queryValue: "전북특별자치도 군산시",
      },
      {
        code: "5214000000",
        label: "익산시",
        queryValue: "전북특별자치도 익산시",
      },
      {
        code: "5218000000",
        label: "정읍시",
        queryValue: "전북특별자치도 정읍시",
      },
      {
        code: "5219000000",
        label: "남원시",
        queryValue: "전북특별자치도 남원시",
      },
      {
        code: "5221000000",
        label: "김제시",
        queryValue: "전북특별자치도 김제시",
      },
      {
        code: "5271000000",
        label: "완주군",
        queryValue: "전북특별자치도 완주군",
      },
      {
        code: "5272000000",
        label: "진안군",
        queryValue: "전북특별자치도 진안군",
      },
      {
        code: "5273000000",
        label: "무주군",
        queryValue: "전북특별자치도 무주군",
      },
      {
        code: "5274000000",
        label: "장수군",
        queryValue: "전북특별자치도 장수군",
      },
      {
        code: "5275000000",
        label: "임실군",
        queryValue: "전북특별자치도 임실군",
      },
      {
        code: "5277000000",
        label: "순창군",
        queryValue: "전북특별자치도 순창군",
      },
      {
        code: "5279000000",
        label: "고창군",
        queryValue: "전북특별자치도 고창군",
      },
      {
        code: "5280000000",
        label: "부안군",
        queryValue: "전북특별자치도 부안군",
      },
    ],
  },
  {
    sourceCode: "1200000000",
    label: "전라남도",
    queryValue: "전라남도",
    provinceOnly: false,
    districts: [
      {
        code: "1211000000",
        label: "목포시",
        queryValue: "전라남도 목포시",
      },
      {
        code: "1213000000",
        label: "여수시",
        queryValue: "전라남도 여수시",
      },
      {
        code: "1215000000",
        label: "순천시",
        queryValue: "전라남도 순천시",
      },
      {
        code: "1217000000",
        label: "나주시",
        queryValue: "전라남도 나주시",
      },
      {
        code: "1219000000",
        label: "광양시",
        queryValue: "전라남도 광양시",
      },
      {
        code: "1271000000",
        label: "담양군",
        queryValue: "전라남도 담양군",
      },
      {
        code: "1272000000",
        label: "곡성군",
        queryValue: "전라남도 곡성군",
      },
      {
        code: "1273000000",
        label: "구례군",
        queryValue: "전라남도 구례군",
      },
      {
        code: "1274000000",
        label: "고흥군",
        queryValue: "전라남도 고흥군",
      },
      {
        code: "1275000000",
        label: "보성군",
        queryValue: "전라남도 보성군",
      },
      {
        code: "1276000000",
        label: "화순군",
        queryValue: "전라남도 화순군",
      },
      {
        code: "1277000000",
        label: "장흥군",
        queryValue: "전라남도 장흥군",
      },
      {
        code: "1278000000",
        label: "강진군",
        queryValue: "전라남도 강진군",
      },
      {
        code: "1279000000",
        label: "해남군",
        queryValue: "전라남도 해남군",
      },
      {
        code: "1280000000",
        label: "영암군",
        queryValue: "전라남도 영암군",
      },
      {
        code: "1281000000",
        label: "무안군",
        queryValue: "전라남도 무안군",
      },
      {
        code: "1282000000",
        label: "함평군",
        queryValue: "전라남도 함평군",
      },
      {
        code: "1283000000",
        label: "영광군",
        queryValue: "전라남도 영광군",
      },
      {
        code: "1284000000",
        label: "장성군",
        queryValue: "전라남도 장성군",
      },
      {
        code: "1285000000",
        label: "완도군",
        queryValue: "전라남도 완도군",
      },
      {
        code: "1286000000",
        label: "진도군",
        queryValue: "전라남도 진도군",
      },
      {
        code: "1287000000",
        label: "신안군",
        queryValue: "전라남도 신안군",
      },
    ],
  },
  {
    sourceCode: "4700000000",
    label: "경상북도",
    queryValue: "경상북도",
    provinceOnly: false,
    districts: [
      {
        code: "4711000000",
        label: "포항시",
        queryValue: "경상북도 포항시",
      },
      {
        code: "4711100000",
        label: "포항시남구",
        queryValue: "경상북도 포항시남구",
      },
      {
        code: "4711300000",
        label: "포항시북구",
        queryValue: "경상북도 포항시북구",
      },
      {
        code: "4713000000",
        label: "경주시",
        queryValue: "경상북도 경주시",
      },
      {
        code: "4715000000",
        label: "김천시",
        queryValue: "경상북도 김천시",
      },
      {
        code: "4717000000",
        label: "안동시",
        queryValue: "경상북도 안동시",
      },
      {
        code: "4719000000",
        label: "구미시",
        queryValue: "경상북도 구미시",
      },
      {
        code: "4721000000",
        label: "영주시",
        queryValue: "경상북도 영주시",
      },
      {
        code: "4723000000",
        label: "영천시",
        queryValue: "경상북도 영천시",
      },
      {
        code: "4725000000",
        label: "상주시",
        queryValue: "경상북도 상주시",
      },
      {
        code: "4728000000",
        label: "문경시",
        queryValue: "경상북도 문경시",
      },
      {
        code: "4729000000",
        label: "경산시",
        queryValue: "경상북도 경산시",
      },
      {
        code: "4773000000",
        label: "의성군",
        queryValue: "경상북도 의성군",
      },
      {
        code: "4775000000",
        label: "청송군",
        queryValue: "경상북도 청송군",
      },
      {
        code: "4776000000",
        label: "영양군",
        queryValue: "경상북도 영양군",
      },
      {
        code: "4777000000",
        label: "영덕군",
        queryValue: "경상북도 영덕군",
      },
      {
        code: "4782000000",
        label: "청도군",
        queryValue: "경상북도 청도군",
      },
      {
        code: "4783000000",
        label: "고령군",
        queryValue: "경상북도 고령군",
      },
      {
        code: "4784000000",
        label: "성주군",
        queryValue: "경상북도 성주군",
      },
      {
        code: "4785000000",
        label: "칠곡군",
        queryValue: "경상북도 칠곡군",
      },
      {
        code: "4790000000",
        label: "예천군",
        queryValue: "경상북도 예천군",
      },
      {
        code: "4792000000",
        label: "봉화군",
        queryValue: "경상북도 봉화군",
      },
      {
        code: "4793000000",
        label: "울진군",
        queryValue: "경상북도 울진군",
      },
      {
        code: "4794000000",
        label: "울릉군",
        queryValue: "경상북도 울릉군",
      },
    ],
  },
  {
    sourceCode: "4800000000",
    label: "경상남도",
    queryValue: "경상남도",
    provinceOnly: false,
    districts: [
      {
        code: "4812000000",
        label: "창원시",
        queryValue: "경상남도 창원시",
      },
      {
        code: "4812100000",
        label: "창원시의창구",
        queryValue: "경상남도 창원시의창구",
      },
      {
        code: "4812300000",
        label: "창원시성산구",
        queryValue: "경상남도 창원시성산구",
      },
      {
        code: "4812500000",
        label: "창원시마산합포구",
        queryValue: "경상남도 창원시마산합포구",
      },
      {
        code: "4812700000",
        label: "창원시마산회원구",
        queryValue: "경상남도 창원시마산회원구",
      },
      {
        code: "4812900000",
        label: "창원시진해구",
        queryValue: "경상남도 창원시진해구",
      },
      {
        code: "4817000000",
        label: "진주시",
        queryValue: "경상남도 진주시",
      },
      {
        code: "4822000000",
        label: "통영시",
        queryValue: "경상남도 통영시",
      },
      {
        code: "4824000000",
        label: "사천시",
        queryValue: "경상남도 사천시",
      },
      {
        code: "4825000000",
        label: "김해시",
        queryValue: "경상남도 김해시",
      },
      {
        code: "4827000000",
        label: "밀양시",
        queryValue: "경상남도 밀양시",
      },
      {
        code: "4831000000",
        label: "거제시",
        queryValue: "경상남도 거제시",
      },
      {
        code: "4833000000",
        label: "양산시",
        queryValue: "경상남도 양산시",
      },
      {
        code: "4872000000",
        label: "의령군",
        queryValue: "경상남도 의령군",
      },
      {
        code: "4873000000",
        label: "함안군",
        queryValue: "경상남도 함안군",
      },
      {
        code: "4874000000",
        label: "창녕군",
        queryValue: "경상남도 창녕군",
      },
      {
        code: "4882000000",
        label: "고성군",
        queryValue: "경상남도 고성군",
      },
      {
        code: "4884000000",
        label: "남해군",
        queryValue: "경상남도 남해군",
      },
      {
        code: "4885000000",
        label: "하동군",
        queryValue: "경상남도 하동군",
      },
      {
        code: "4886000000",
        label: "산청군",
        queryValue: "경상남도 산청군",
      },
      {
        code: "4887000000",
        label: "함양군",
        queryValue: "경상남도 함양군",
      },
      {
        code: "4888000000",
        label: "거창군",
        queryValue: "경상남도 거창군",
      },
      {
        code: "4889000000",
        label: "합천군",
        queryValue: "경상남도 합천군",
      },
    ],
  },
  {
    sourceCode: "5000000000",
    label: "제주특별자치도",
    queryValue: "제주특별자치도",
    provinceOnly: false,
    districts: [
      {
        code: "5011000000",
        label: "제주시",
        queryValue: "제주특별자치도 제주시",
      },
      {
        code: "5013000000",
        label: "서귀포시",
        queryValue: "제주특별자치도 서귀포시",
      },
    ],
  },
] as const satisfies readonly LessonRegion[]
